backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    format: 'frontmatter'
    folder: 'assets/content/pages'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'jobs'
        label: 'Jobs'
        widget: 'list'
        fields:
          - { label: 'Company', name: 'company', widget: 'string' }
          - { label: 'Start Date', name: 'startDate', widget: 'datetime', timeFormat: false }
          - { label: 'End Date', name: 'endDate', widget: 'datetime', required: false, timeFormat: false }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - name: 'projects'
        label: 'Projects'
        widget: 'list'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - name: 'certs'
        label: 'Certifications'
        widget: 'list'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
  